### ISSUE TITLE
add a way to limit multiple programs at the same time

### ISSUE THREAD

**Issue by rgndxzzk** [0vm/RAM-Limiter#1]
i want to limit discord, firefox, spotify, steamwebhelper all at the same time but i will have to run the program four times to do this; is there a way on the custom process option to add multiple processes (that can be separated with commas)?
i feel like it would also be helpful to apply this through launch arguments or some sort of configuration file

**Comment by 0vm** [comment]
Never thought of it that way, thank you for the input!
Will add comma formatting in the next update, but launch arguments will be a bit tricky.

**Comment by rgndxzzk** [comment]
you could add --set-custom-processes (to select the 5th option by startup) then --config "textfile.cfg" and have it set the processes that are in that textfile

**Comment by 0vm** [comment]
I will have to make it create a new thread based on how many programs are inserted, so that will be a bit tricky, I am working on it though.

**Comment by 0vm** [comment]
![image](https://github.com/0vm/RAM-Limiter/assets/79897291/3e9c58bc-4bae-4e43-afc8-32d7aae4010c)
good news, haven't started on launch arguments yet

**Comment by 0vm** [comment]
https://github.com/0vm/RAM-Limiter/releases/tag/main

I am closing this issue now. If you encounter any further problems or have any new suggestions, please don't hesitate to reach out again!

**Comment by 0vm** [comment]
Configuration file will come soon.

**Comment by 0vm** [comment]
I had not paid much attention to this repo, and it has just hit 100 stars, so I will add a config.
